# Generated by Django 5.0.6 on 2024-06-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_questionpaper_quest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quest_type',
            field=models.IntegerField(choices=[(0, 'Coding'), (1, 'MCQ'), (2, 'Free Test')], default=0),
        ),
    ]
