# Generated by Django 5.0.6 on 2024-06-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_academicfield_college_country_academicbranch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='mcqresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='mcquestions',
            name='question',
        ),
        migrations.RemoveField(
            model_name='test',
            name='org',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='test',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question_paper',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='MCQResponse',
        ),
        migrations.DeleteModel(
            name='MCQuestions',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionPaper',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
